Public Class Update
    Public Property version() As String = ""
    Public Property vpn_list() As String = ""
    Public Property vpn_list2() As String = ""
    Public Property vpn_list3() As String = ""
    Public Property vpn_list4() As String = ""
    Public Property indo() As String = ""
    Public Property indo2() As String = ""
    Public Property indo3() As String = ""
    Public Property singa() As String = ""
    Public Property download() As String = ""
    Public Property ip() As String = ""
    Public Property ip2() As String = ""
    Public Property ip3() As String = ""
    Public Property ip4() As String = ""
    Public Property Japan() As String = ""
    Public Property Japan2() As String = ""
    Public Property Japan3() As String = ""
    Public Property Jap() As String = ""
    Public Property Jap2() As String = ""
    Public Property Jap3() As String = ""
    Public Property sing() As String = ""

End Class
